default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

local: &local
  adapter: postgresql
  encoding: unicode
  pool: 5
  
development:
  <<: *local
  database: dev/new_task_list


test:
  <<: *local
  database: test/new_task_list
